apiVersion: v1
kind: Service
metadata:
  name: scaling-model-service
spec:
  selector:
    app: scaling-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Change to NodePort if running locally
