apiVersion: v1
kind: Pod
metadata:
  name: ganache
  labels:
    app: ganache
spec:
  containers:
    - name: ganache
      image: trufflesuite/ganache-cli
      args: ["--deterministic"]
      ports:
        - containerPort: 8545
